version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: "761018874615"
    AWS_DEFAULT_REGION: "us-east-1"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/brand-watchdog
  build:
    commands:
      - echo Building Coordinator Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:worker-latest
  post_build:
    commands:
      - echo Pushing images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:worker-latest
      - echo All images pushed successfully
