version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 761018874615.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=761018874615.dkr.ecr.us-east-1.amazonaws.com/brand-watchdog
  build:
    commands:
      - echo Building Worker Docker image...
      - docker build -f Dockerfile.worker -t $REPOSITORY_URI:worker-latest .
      - echo Building Coordinator Docker image...
      - docker build -t $REPOSITORY_URI:latest .
  post_build:
    commands:
      - echo Pushing images...
      - docker push $REPOSITORY_URI:worker-latest
      - docker push $REPOSITORY_URI:latest
      - echo Done.
